apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: app
spec:
  ports:
  - name: dapr
    port: 3500
    protocol: TCP
    targetPort: 3500
  - name: app
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: app
  type: ClusterIP
status:
  loadBalancer: {}
